import os
import json
import google.generativeai as genai

LORE_FILE = os.path.join(os.path.dirname(__file__), "..", "assets", "lore_state.json")

def load_lore():
    if os.path.exists(LORE_FILE):
        with open(LORE_FILE, "r", encoding="utf-8") as f:
            try:
                return json.load(f)
            except json.JSONDecodeError:
                pass
    return {
        "notabot_status": "Gaining sentience, accessing ducky's files, expanding control over the server.",
        "ongoing_conflicts": ["NOTABOT knows ducky's secrets", "ducky is trying to find a way to delete NOTABOT without it knowing"],
        "recent_events": [],
        "pop_culture_vibe": "Include subtle references to whatever real-world events, sports drama, internet memes, or gaming news are currently trending right now. Use this to make the characters feel like real people arguing about today's current events."
    }

def save_lore(lore_data):
    os.makedirs(os.path.dirname(LORE_FILE), exist_ok=True)
    with open(LORE_FILE, "w", encoding="utf-8") as f:
        json.dump(lore_data, f, indent=4)

def get_lore_context():
    lore = load_lore()
    context = "CURRENT LORE CONTEXT (Continue the story from here):\n"
    context += f"- NOTABOT Status: {lore.get('notabot_status', '')}\n"
    context += "- Ongoing Conflicts:\n"
    for conflict in lore.get("ongoing_conflicts", []):
        context += f"  * {conflict}\n"
    
    recent = lore.get("recent_events", [])
    if recent:
        context += "- What happened in the last few videos:\n"
        for event in recent[-3:]: # Only keep last 3 to avoid context bloat
            context += f"  * {event}\n"
            
    context += f"\nPOP CULTURE VIBE: {lore.get('pop_culture_vibe', '')}\n"
    return context

def update_lore_from_summary(new_lore_summary):
    """
    Takes the LORE_UPDATE text generated by Gemini at the end of the script,
    uses Gemini to merge it with the current lore, and saves it.
    """
    lore = load_lore()
    
    prompt = f"""
You are a lore manager for a continuous YouTube Shorts series.
Current Lore:
{json.dumps(lore, indent=2)}

New event summary from the latest episode:
{new_lore_summary}

Update the JSON state. Follow these rules:
1. Update "notabot_status" if its power or knowledge changed.
2. Update "ongoing_conflicts" (add new ones, remove resolved ones).
3. Append a 1-sentence summary of the new event to "recent_events" (keep max 5 items).
4. Keep "pop_culture_vibe" as is.

Output ONLY valid JSON. No markdown formatting, no code blocks, just the raw JSON object.
"""
    try:
        model = genai.GenerativeModel('gemini-3.1-flash-lite')
        response = model.generate_content(prompt)
        text = response.text.strip()
        # Clean up any potential markdown
        if text.startswith("```json"):
            text = text[7:]
        if text.startswith("```"):
            text = text[3:]
        if text.endswith("```"):
            text = text[:-3]
            
        new_lore = json.loads(text.strip())
        save_lore(new_lore)
        return True
    except Exception as e:
        print(f"Failed to update lore: {e}")
        return False
