import os
import subprocess

def make_vertical():
    """
    This step is now handled directly inside compile_images.py via moviepy.
    compile_images.py outputs vertical_short.mp4 in 1080x1920 directly,
    so this script is a no-op. It's kept for backwards compatibility.
    """
    root_dir = os.path.join(os.path.dirname(__file__), "..")
    output_path = os.path.join(root_dir, "vertical_short.mp4")
    
    if os.path.exists(output_path):
        print(f"vertical_short.mp4 already exists (generated by compile_images.py). Nothing to do.")
    else:
        print(f"Warning: vertical_short.mp4 not found. Run auto_main.py to generate it.")
        
if __name__ == "__main__":
    make_vertical()
